version: '3'
services:

  app:
    container_name: docker-node-mysql
    depends_on:
      - db
    links:
      - db
    restart: always
    build: .
    image: boilerplatemysql:1.0.0
    ports:
      - '9890:9890'
    external_links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3389:3306"
    expose: 
      - "3389" 
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: Udaipur12345#
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: root
      MYSQL_PASSWORD: Udaipur12345#
    volumes:
      - /var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    
